### PR TITLE
Fixes #4417 from completions incorrectly autocomplete

### LINKED ISSUE #4417: from completions incorrectly autocomplete
with django installed, type:

```
from django.for
```

1. Completions appear after you type `django.`, but as you type `for`, they don't track in the combo box, ie 'focus' stays on first item. This is different behavior compared to `import django.for`.
image

2. Doesn't matter if completions combo box is still up or not, if you press control+space in the hopes of getting `forms`, you'll get `forimport` instead.
image

### PR DESCRIPTION
**Pull request by zooba**
Fixes #4417 from completions incorrectly autocomplete
Fixes selection of applicable span for from names.

### CODE REVIEW

**Comment by huguesv** [comment]
That works better, but I noticed this:
```
from django.forms im
```

put caret at the end and press ctrl+space and you'll get:
```
from django.forms imimport
```

**Comment by huguesv** [comment]
Completions don't automatically appear after a comma, and a ctrl+space doesn't bring them up either.
image

**Comment by zooba** [comment]
I was seeing that latter one as well - are you on the latest internal VS build? I think it's flakey... the completions are definitely being returned, but the session is being dismissed instead of started.

**Comment by huguesv** [comment]
I'm on Preview 3 [27818], I'll update to 27820 later.

I can file that bug separately, I don't want to pile on bugs and make this PR never ending, but wanted to give you the chance to get the fix in if it's quick/easy.

**Comment by zooba** [comment]
The incomplete "import" case is looking kinda tough, just because of the way we build the AST in that situation. I think I have an easy workaround for it, but if not then it'll just have to stick around for a bit.

**Comment by huguesv** [comment]
The fix for `imimport` looks ok.

It's somewhat ridiculous to be completing this because you might as well type `s`:
```from django.forms import BaseForm a```
after ctrl+space becomes:
```from django.forms import BaseForm aas```

**Comment by huguesv** [comment]
Sometimes ctrl+space after this:
```from django.forms import BaseForm, BaseFormS```
becomes
```from django.forms import BaseForm, BaseFormSas```
instead of getting the completions drop down.

**Comment by zooba** [comment]
The "as" completion matters because it should appear after typing the space. So you can do `from<space>dj<space><tab><space>Base<space><tab><space>AsNameForBaseForm`. But it's hard to get perfectly right with incomplete statements. The same check as I added for import should also work for as though.

**Pull request merged**
