### PR TITLE
Fixes #3866 Endlessly analyzing sympy

### LINKED ISSUE #3866: Asserts building completion DB for Anaconda 5.0
With Completion DB feature, I let it analyze the whole environment (it took anywhere between 50 and 2 hours) and when I went to use it it said it wasn't up to date. So I clicked Refresh DB and it's analyzing slowly, and I got 5 consecutive assertions. I broke in the debugger to see what it was analyzing.

((Microsoft.PythonTools.Analysis.ProjectEntry)((Microsoft.PythonTools.Analysis.Values.GeneratorInfo)(new Microsoft.PythonTools.Analysis.AnalysisSetDetails.DebugViewProxy(set).Data[0]))._declaringModule).ModuleName
lib2to3.pgen2.tokenize

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Item generator[{None, tuple, }] (57823608) and generator[{None, tuple, }] (57823608) should have been combined already by comparer {set.Comparer}



   at Microsoft.PythonTools.Analysis.AnalysisSet.Trim(IAnalysisSet set) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\AnalysisSet.cs:line 418

   at Microsoft.PythonTools.Analysis.AnalysisSetDetails.AnalysisSetOneUnion.Union(IEnumerable`1 items, Boolean canMutate) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\AnalysisSet.cs:line 1089

   at Microsoft.PythonTools.Analysis.TypedDef`1.get_TypesNoCopy() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\VariableDef.cs:line 348

   at Microsoft.PythonTools.Analysis.TypedDef`1.get_Types() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\VariableDef.cs:line 369

   at Microsoft.PythonTools.Analysis.Values.InstanceInfo.GetMember(Node node, AnalysisUnit unit, String name) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Values\InstanceInfo.cs:line 189

   at Microsoft.PythonTools.Analysis.AnalysisValueSetExtensions.GetMember(IAnalysisSet self, Node node, AnalysisUnit unit, String name) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\AnalysisValueSetExtensions.cs:line 40

   at Microsoft.PythonTools.Analysis.Analyzer.ExpressionEvaluator.EvaluateMember(ExpressionEvaluator ee, Node node) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Analyzer\ExpressionEvaluator.cs:line 299

   at Microsoft.PythonTools.Analysis.Analyzer.ExpressionEvaluator.EvaluateWorker(Node node) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Analyzer\ExpressionEvaluator.cs:line 220

   at Microsoft.PythonTools.Analysis.Analyzer.ExpressionEvaluator.Evaluate(Expression node) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Analyzer\ExpressionEvaluator.cs:line 56

   at Microsoft.PythonTools.Analysis.Analyzer.ExpressionEvaluator.Evaluate(IList`1 nodes) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Analyzer\ExpressionEvaluator.cs:line 212

   at Microsoft.PythonTools.Analysis.Analyzer.ExpressionEvaluator.EvaluateCall(ExpressionEvaluator ee, Node node) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Analyzer\ExpressionEvaluator.cs:line 380

   at Microsoft.PythonTools.Analysis.Analyzer.ExpressionEvaluator.EvaluateWorker(Node node) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Analyzer\ExpressionEvaluator.cs:line 220

   at Microsoft.PythonTools.Analysis.Analyzer.ExpressionEvaluator.Evaluate(Expression node) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Analyzer\ExpressionEvaluator.cs:line 56

   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(AssignmentStatement node) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Analyzer\DDG.cs:line 147

   at Microsoft.PythonTools.Parsing.Ast.AssignmentStatement.Walk(PythonWalker walker) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Parsing\Ast\AssignmentStatement.cs:line 41

   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(SuiteStatement node) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Analyzer\DDG.cs:line 524

   at Microsoft.PythonTools.Parsing.Ast.SuiteStatement.Walk(PythonWalker walker) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Parsing\Ast\SuiteStatement.cs:line 34

   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(WhileStatement node) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Analyzer\DDG.cs:line 595

   at Microsoft.PythonTools.Parsing.Ast.WhileStatement.Walk(PythonWalker walker) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Parsing\Ast\WhileStatement.cs:line 64

   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Walk(SuiteStatement node) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Analyzer\DDG.cs:line 524

   at Microsoft.PythonTools.Parsing.Ast.SuiteStatement.Walk(PythonWalker walker) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Parsing\Ast\SuiteStatement.cs:line 34

   at Microsoft.PythonTools.Analysis.Analyzer.FunctionAnalysisUnit.AnalyzeWorker(DDG ddg, CancellationToken cancel) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Analyzer\FunctionAnalysisUnit.cs:line 86

   at Microsoft.PythonTools.Analysis.AnalysisUnit.Analyze(DDG ddg, CancellationToken cancel) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\AnalysisUnit.cs:line 151

   at Microsoft.PythonTools.Analysis.Analyzer.DDG.Analyze(Deque`1 queue, CancellationToken cancel, Action`1 reportQueueSize, Int32 reportQueueInterval) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Analyzer\DDG.cs:line 76

   at Microsoft.PythonTools.Analysis.PythonAnalyzer.AnalyzeQueuedEntries(CancellationToken cancel) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\PythonAnalyzer.cs:line 1036

   at Microsoft.PythonTools.Analysis.PyLibAnalyzer.Analyze() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analyzer\PyLibAnalyzer.cs:line 1368

   at Microsoft.PythonTools.Analysis.PyLibAnalyzer.<RunWorker>d__34.MoveNext() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analyzer\PyLibAnalyzer.cs:line 208

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()

   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)

   at System.Threading.Tasks.Task.FinishContinuations()

   at System.Threading.Tasks.Task.FinishStageThree()

   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetResult()

   at Microsoft.PythonTools.Analysis.PyLibAnalyzer.<Scrape>d__60.MoveNext() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analyzer\PyLibAnalyzer.cs:line 1163

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()

   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)

   at System.Threading.Tasks.Task.FinishContinuations()

   at System.Threading.Tasks.Task.FinishStageThree()

   at System.Threading.Tasks.Task.FinishStageTwo()

   at System.Threading.Tasks.Task.Finish(Boolean bUserDelegateExecuted)

   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)

   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)

   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()

   at System.Threading.ThreadPoolWorkQueue.Dispatch()

   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()


---------------------------
Abort   Retry   Ignore   
---------------------------
```

### PR DESCRIPTION
**Pull request by zooba**
Fixes #3866 Endlessly analyzing sympy
Fixes 'type' comparison
Reduces analysis when merging all function calls
Adds simple cache for VariableDef to improve performance when a function has many callers

### CODE REVIEW

**Comment by huguesv** [comment]
It completes analysis of sympy, but there are no completions.
That's better than before, but just curious if you are expecting this.
image

**Comment by huguesv** [comment]
Have you done a complete analysis of Anaconda too? I'm worried about regressions in other packages.

**Comment by huguesv** [comment]
I wiped the completion db folder and tried to refresh the DB for Anaconda 4.4.10, and it stops analyzing but the list is missing several packages. I've put the diagnostics in `bugs\3866\Diagnostic Info 2018-04-17T130119.txt`

**Comment by huguesv** [comment]
Disregard that last comment, I accidentally analyzed miniconda instead of anaconda...

**Comment by huguesv** [comment]
Fully analyzed Anaconda 5.0. No completions on sympy, but other packages still do.

**Comment by zooba** [comment]
@huguesv Can you grab the .idb files for sympy? It should have results (mine does)

**Comment by huguesv** [comment]
I copied the .idb files to `bugs\3866`

**Comment by zooba** [comment]
They were definitely analysed properly. Guess there's something up with loading... shouldn't block this PR, in my opinion, and it's probably not real high priority anymore either.

**Comment by zooba** [comment]
Also, do you want this backported for 15.7?

**Comment by huguesv** [comment]
Yes, we should backport to 15.7

**Pull request merged**
