### PR TITLE
[WIP] Send event on unhandled exceptions

### LINKED ISSUE #3946: Add event for unexpected error
Our unexpected error handling that brings up a dialog prevents VS from crashing, which means no Watson crash report. We need a way to measure the impact of these errors (not everyone files an issue when they see the dialog).

### PR DESCRIPTION
**Pull request by huguesv**
Fix #3946

### CODE REVIEW

**Comment by zooba** [comment]
We almost certainly want to use `PostFault` rather than `PostEvent`. Haven't looked into the rest of the PR yet though.

**Comment by zooba** [comment]
I'd kind of like this to go through the existing logging infrastructure, so that the in-memory logger can also collect these events, and we can also keep the telemetry pieces all in the one spot. That may not work with cookiecutter though, as we don't have the references there for it... any reason you didn't put it with the existing support?

**Comment by huguesv** [comment]
1. Cookiecutter would have required a different implementation (all the telemetry classes are different).
2. No need to log to in-memory logger since we already fetch from the Windows Event log when building diagnostics info.
3. This can work before our PythonToolsLogger is created.

**Comment by zooba** [comment]
1 is valid. 3 is irrelevant (if we're throwing unhandled errors during load then we can't recover through our own dialog), and if we log through the logger then there's no need to fetch the event log anymore (which is one of the slowest parts of building the diagnostic info).

Not sure if 1 alone is a good enough reason, especially since it seems like it needs to be a different implementation anyway?

**Pull request closed without merging**
