### PR TITLE
Added Automatic Brace Completion #808

### PR DESCRIPTION
**Pull request by martinzimmermann**
This enables Automatic Brace Completion the solution is very similar to that, that @crwilcox  suggested.

### CODE REVIEW

**Comment by zooba** [comment]
Looks good! The one bit that bothers me is the helper function in the test to enable/disable brace completion. We used to have code like that all over the place and it is notoriously unreliable.

It should be possible to get at the setting through DTE, as we do in a few other places. When I get a bit of time, I'll see if I can track down the names needed to find the setting.

**Comment by martinzimmermann** [comment]
Jeah, I didn’t like it either. I tried to get it working through DTE but after a few hours I gave up. A MSDN article suggested that the names can be found in the registry, but I wasn’t able to locate the TextEditor -> Python -> General option page. 

If you can point me in the right direction I can also update the test myself.

**Comment by zooba** [comment]
Sorry I took so long to get around to this - things have been very busy here. Because of the conflicts (which weren't real conflict), I've merged this by hand. Hopefully is still has your name on it, but I can't be sure of that (wasn't a regular git merge... git and I don't get along that well :) )

You'll see it appear in our next major update, which is going to be a while away yet (preview builds coming soon though), but congrats on being the first external contributor for it!

**Comment by martinzimmermann** [comment]
I think something went wrong, because it is not associated with my Github account (Github associates commits by commit email as far as I know) however I don’t care as long as it is fixed.

Also I’m very honored to be the first external contributor (I probably should commit another thing to claim that status officially :stuck_out_tongue_winking_eye:)

**Comment by zooba** [comment]
Yeah, I think the email got dropped when I moved it :( Sorry about that.

You're more than welcome to contribute more (though it is only first external contributor _for our next release_ - but there haven't been many in the past, so you're probably still in the first 10 ;) )

**Pull request closed without merging**
