### PR TITLE
Fix debugger test failures

### PR DESCRIPTION
**Pull request by huguesv**
Don't add the ptvsd_launcher.py parent folder to the PREFIXES array of standard library folders. The ptvsd files are already in the DONT_DEBUG array of files to never debug.

### CODE REVIEW

**Comment by zooba** [comment]
Do we know why that line was added in the first place?

**Comment by huguesv** [comment]
You said "Fixes ptvsd directory not being excluded" but I'm not sure what were the repro steps for that.
https://github.com/Microsoft/PTVS/commit/2b56096fbd001bc1ea5acb9397acf77873f50c16

**Comment by zooba** [comment]
Ah, I was trying to hide the ptvsd modules from the modules window. I bet they're showing up again now, or they may be showing up as "user code" - I don't think we filter these using `DONT_DEBUG`.

**Comment by huguesv** [comment]
Yeah they show up in modules window. Since we pretend that ptvsd doesn't exist when debugging (always removed from call stack) then we probably don't want to skip sending the module loaded event for them (DONT_DEBUG) as well, all the time?

**Comment by zooba** [comment]
I think what you're saying is "we should skip sending module load events for items in DONT_DEBUG"? If so, yeah, let's just do that.

**Pull request merged**
