### PR TITLE
Improvements to C++ symbol parsing and support for VTune2019 

### PR DESCRIPTION
**Pull request by rgesteve**
Addresses feedback in #4775 (thanks,  @hughesv !) and rebases.  I mean to delete the aforementioned PR, please consider this one instead.  #4775 only left for reference on feedback.

### CODE REVIEW

**Comment by huguesv** [comment]
Thanks! There are still several comments from the old PR that aren't addressed but still apply.

**Comment by huguesv** [comment]
Also, there are no tests at all. If we want to include this in the product, we'll need to have a way of catching regressions.

At a minimum, there's a lot of converter/parser code that can be tested by including input files under TestData folder, without the need to run profiling and have vtune installed to run the tests. They can be added to ProfilingTests project.

**Comment by rgesteve** [comment]
Sorry for the delay, @MinKPark, updating this code to VTune free version.  Will include instructions on how to test/use with "community edition" of VTune.  Thanks @huguesv for closing the other PR.

**Comment by huguesv** [comment]
@rgesteve 
I'm closing since there's been no progress in the past 6 months and I'm tidying up the open PR list for the new year.

We're still interested in having this functionality, so whenever you make progress and it's ready for review, feel free to reopen this one or open a new PR.

**Pull request closed without merging**
