### PR TITLE
Resolves: Add native GitHub security and versioning dependency alerts

### LINKED ISSUE #6615: Add native GitHub security and versioning dependency alerts
- [Dependabot](https://dependabot.com/) alerts on updates for the project's dated and vulnerable dependencies and automatically creates PRs to easily update them

Pipeline Foundation is **a non-profit initiative** with the sole purpose of giving back to the IT community by assisting OSS projects with DevOps implementations and best practices.

Built with ❤ by [Pipeline Foundation](https://pipeline.foundation).

### PR DESCRIPTION
**Pull request by aleks-ivanov**
- add `dependabot.yml` which automatically enables Dependabot's dependency versioning scanner and dependency update PRs bot by declaring dependency ecosystems and sources in the project. For dependency security vulnerabilities scanner and vulnerable dependency update PRs bot, [enable "Dependabot alerts" and "Dependabot security updates"](https://docs.github.com/en/github/managing-security-vulnerabilities/configuring-dependabot-security-updates)

- use the `target-branch` attribute, if you would like to run Dependabot's scan against a branch other than your default branch (for example if you have a separate development branch)

- should you decide that certain people on your team should take care of the PRs that Dependabot creates, use the two attributes `assignees` and `reviewers` to automatically set personnel respectively.

Resolves #6615

### CODE REVIEW

**Comment by aleks-ivanov** [comment]
To allow Dependabot suggest updates for dependencies from `https://pkgs.dev.azure.com/devdiv/_packaging/Pylance/npm/registry`:

- add registry token as GitHub secret with the name NPM_PRIVATE_REG_TOKEN

**Comment by rchiodo** [comment]
What is the side effect of turning on this dependabot? Will it start creating PRs to update our nuget dependencies? All but one are generated by Microsoft and are hand controlled to match a specific build of VS, so not sure what the dependabot would do. 

I guess I'm not sure we need this.

**Comment by aleks-ivanov** [comment]
Yes, the Dependabot YAML configuration enables the bot that creates PRs with version updates for dependencies.

With the current configuration, it is instructed to look for updates in all nuget, npm and pip dependency sources in the project (tests involved sources excluded).

It can be tailored towards to a specific one or only few sources that would be helpful for the PTVS project and not generate unnecessary PRs. 

We can do that if you'd like. 🙂

**Comment by rchiodo** [comment]
@aleks-ivanov sorry for the delay. I'm waiting on @AdamYoblick to return from being OOF to see what he thinks. I'm not sure I want dependabot updating anything at the moment, but Adam may feel differently.

**Comment by rchiodo** [comment]
Closing for now as both Adam and I think we don't need dependabot.

**Pull request closed without merging**
