### PR TITLE
Fixes #3625 "Format Document" adds invalid code

### LINKED ISSUE #3625: "Format Document" adds invalid code
Build from 15.6rel, commit 2c03499

1. Open `test_userdict.py` from `python2.7\test`
2. Call `Edit -> Advanced -> Format Document`

Actual: command replaces first line 
```python
# Check every path through every method of UserDict
```
with 
```python
from test import test_support, mapping_testsclass SeqDict(UserDict.DictMixin):    test_support.run_unittest(UserDictTest,        UserDictMixinTest)erDict
```

Bug is somewhere in `NewLineLocation.LocationToIndex`

### PR DESCRIPTION
**Pull request by zooba**
Fixes #3625 "Format Document" adds invalid code
Ensures LineInfo.LineNumber is correctly initialized
Simplifies analysis protocol messages for formatting

All the tests pass manually, though some UI tests are still flakey.

### CODE REVIEW

**Comment by AlexanderSher** [comment]
With this fix applied, I get "Buffer content mismatch" error more often.

**Comment by AlexanderSher** [comment]
I have stable repro:
1. Open `test_userdict.py`
2. `Edit -> Advanced -> Format Document`
3. `Undo (Ctrl+Z)`
4. `Select All (Ctrl+A)`
5. `Edit -> Advanced -> Format Selection`

**Comment by zooba** [comment]
Ignoring the buffer content mismatch error (which has multiple other bugs already), do you still see the formatting problem?

**Comment by zooba** [comment]
The changes from here are in #3642 now.

**Pull request closed without merging**
