### PR TITLE
VS2015 images

### PR DESCRIPTION
**Pull request by zooba**
Finishes the update to use image monikers throughout the project system on VS 2015. You now need to explicitly suppress Obsolete warnings to continue to use image lists.

Custom images can be added to the set of available monikers where necessary - see `IVsImageService2` for the APIs (this isn't necessary for PTVS as all of our images are included).

### CODE REVIEW

**Comment by int19h** [comment]
:+1:

**Comment by zooba** [comment]
@mousetraps is probably interested in this too...

**Comment by crwilcox** [comment]
:+1: with comments

**Comment by int19h** [comment]
:+1:

**Pull request merged**
