### PR TITLE
Enables better detection of installed Win10 SDK.

### PR DESCRIPTION
**Pull request by zooba**

### CODE REVIEW

**Comment by zooba** [comment]
Feel free to merge after approval.

**Comment by huguesv** [comment]
This means we'll build with Windows 10 SDK instead of Windows 8? Does the Windows 10 SDK drop support of OSes that we still need?

**Comment by huguesv** [comment]
I guess if the rest of VS builds with Win 10 SDK, then that works for us too.

**Comment by zooba** [comment]
The SDK is actually fully backwards compatible, so it's not a big deal. The bigger problem is that VS can only automatically find the Win 8 SDK, and you need to specify a specific Win10 SDK (which is pointless...)

This code is very similar to what I contributed to CPython to solve the same problem.

**Comment by zooba** [comment]
@huguesv Can you merge this once you've merged your own? I'd rather the test fix go in first.

**Pull request merged**
