### PR TITLE
UI test refactoring

### PR DESCRIPTION
**Pull request by zooba**
See #3058 

This is a prototype right now for early review. In particular the `UnitTest1.cs` file is representative of what our test modules will end up containing, while the tests become functions embedded into a VSIX.

### CODE REVIEW

**Comment by zooba** [comment]
Still to do:

- [ ] Infer/find VS install
- [ ] Remove extra deployment steps (`PythonTestData.Deploy()`)

**Comment by zooba** [comment]
@huguesv If you'd like to get started migrating tests, feel free to merge this - I won't be touching it this morning. Also, the tests that generate projects currently do not work, and hopefully I'll finish those off later today.

My plan is to have separate test runner DLLs for each test DLL, rather than putting them all in the one assembly, but we can take the opportunity to refactor the UI tests more significantly. Right now my main aim is to just get them all running again.

**Comment by zooba** [comment]
@huguesv Actually, let me know before we merge so I can update the test machine configuration.

**Comment by huguesv** [comment]
I've reviewed most of it to be familiar with the changes. Let's merge. 👍

**Pull request merged**
