### PR TITLE
Fix VS crash when error points to a missing file

### LINKED ISSUE #2816: VS crash when error points to a missing file
Steps to reproduce:
1. Create a VS python project in VS 2017 (15.2), Windows 10
2. Add some files to the project
3. Physically delete one file from disk (leave the file listed in the project)
4. Run pylint -> you'll get at least 1 error message about the missing file
5. Double click that error -> VS will say it's missing and then crash

Not sure this isn't a VS bug but I mostly work in Python so reporting here..

### PR DESCRIPTION
**Pull request by huguesv**
Fix #2816 VS crash when error points to a missing file

Here's the fix in action:
```
---------------------------
Visual Studio - Python support
---------------------------
The document cannot be opened. It has been renamed, deleted or moved.
---------------------------
OK   
---------------------------
```

### CODE REVIEW

**Comment by huguesv** [comment]
Should I have just caught everything that's not a critical exception instead?

**Comment by zooba** [comment]
Maybe there's a narrower place to handle that error inside the function?

Since this crashes, I'd add a handler that uses the ReportUnhandledException extension method to display the dialog that lets people copy the error for us. But keep the specific message.

**Comment by huguesv** [comment]
VS was catching it and putting up the activity log error message, so not technically a crash.

Trying it again I found that the behavior was slightly different based on whether you delete the file from project or from file explorer, so I adjusted the fix for that.

**Comment by zooba** [comment]
👍

**Pull request merged**
