### PR TITLE
Fixing TcpTransport to not use IPHostEntry if specified address is al…

### PR DESCRIPTION
**Pull request by juanyaw**
…ready an IP address

### CODE REVIEW

**Comment by juanyaw** [comment]
#234

**Comment by zooba** [comment]
LGTM, but I'd like @int19h to weigh in too.

**Comment by int19h** [comment]
I'm actually curious why we need this at all. Per MSDN docs for `TcpClient`, even when IPv6 is enabled, it will try that first, but will fall back to IPv4 anyway. Or is this just so that we don't even waste time trying IPv6?

Anyway, it should be better to use the `TcpClient` constructor that takes `AddressFamily` instead, explicitly specifying `AddressFamily.InterNetwork` there, and then call `Connect` passing in the hostname and the port.

**Comment by juanyaw** [comment]
That actually is exactly the issue.  It works eventually, but what ends up happening is that it takes an extra 30-90 seconds to fallback when trying the IPv6 address(es).  This eats up a great amount of time when trying to get that initial connect for us.  I'll look at the alternative way of doing this that you mention

**Comment by juanyaw** [comment]
@int19h It looks like the way you suggested works great and looks much better.  Thanks!

**Comment by int19h** [comment]
:+1:

**Pull request merged**
