### PR TITLE
#247 Parse and analyse async/await syntax

### PR DESCRIPTION
**Pull request by zooba**
Adds support for async/await syntax.
Fixes analysis of user-defined __enter__, __iter__ and __next__/next methods.
Fixes some analysis tests
Fixes AnalysisHashSet to correctly update unioned types.

### CODE REVIEW

**Comment by int19h** [comment]
Can you also make `AwaitExpression` non-side-effect free in `ProximityExpressionWalker`?

**Comment by int19h** [comment]
Might also need an override in `ExpressionCompletionWalker`.

**Comment by zooba** [comment]
Done. I also need to update the method extractor to correctly extract await statements and generate async def.

**Comment by zooba** [comment]
Actually, going to file that as a separate issue so I can defer it temporarily. Need to work on some higher priorities.

**Comment by int19h** [comment]
:+1:

**Pull request merged**
