### PR TITLE
#225 Error while editing

### PR DESCRIPTION
**Pull request by zooba**
Prevents direct access to dictionaries inside scopes and adds locking to all indirect access.
Adds locking to reference collections.

Not sure yet exactly what the perf impact will be, but there doesn't seem to be a cheaper way to avoid the race conditions we currently suffer from - suggestions welcome.

Test to follow (lots of cross-module analysis running on separate threads for a while and seeing whether we crash)

### CODE REVIEW

**Comment by DinoV** [comment]
For NTVS I solved this w/ a thread-safe AnalysisDictionary class which you could re-use for these dictionaries.  At the very least it would be worth comparing the perf of the 2 and going with whichever one is better.

**Comment by zooba** [comment]
I think in this case AnalysisDictionary would perform better, but still suffer from some of the race conditions because it doesn't handle multiple writers. I could be misremembering some of the crashes caused by this, but fairly sure at least one was a case where we had multiple analysis threads somehow.

**Comment by DinoV** [comment]
We shouldn't ever have multiple analysis threads working on the same analysis though...  If that's happening we should track down and fix that bug.  But we can easily end up with multiple analysis threads if we have multiple projects, or 1 project and some loose Python files.

**Comment by zooba** [comment]
You're right. I ported over the dictionary and hashset and it cleared most things up, then I added some fairly tight locks to handle the rest.

**Comment by DinoV** [comment]
LGTM

**Pull request merged**
