### PR TITLE
Disable add/remove PYTHONPATH form search paths until Pylance support…

### PR DESCRIPTION
**Pull request by bschnurr**
…s it.

https://github.com/microsoft/pylance-release/discussions/4049

### CODE REVIEW

**Review by StellaHuang95 — APPROVED** [review]

**Comment by int19h** [comment]
Can you add a comment to the disabled code blocks referencing this issue, so that we don't accidentally clear it out later?

**Comment by AdamYoblick** [comment]
I'm messing with the repo fork PR settings to get past this issue. Give me a few...

**Comment by AdamYoblick** [comment]
Okay, the only remaining issue was that the forked PR build doesn't have permissions to tag the build. But we don't need PR builds to be tagged so I modified PreBuild.ps1 to only tag builds that are not triggered by a PR. Now the PR build seems to be progressing just fine, even from the fork: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=7766166&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=bcef3ffd-f1fa-5dc3-3949-ef4b1fc16bd7

**Comment by AdamYoblick** [comment]
@bschnurr Your PR build is now unblocked, even from forks. Feel free to continue 😄

**Pull request merged**
