### PR TITLE
Update PTVSD to 4.2.7 and add set next statement registry key

### LINKED ISSUE #5177: Set next statement
Update to latest ptvsd and enable the feature.

### PR DESCRIPTION
**Pull request by RaymonGulati1**
Fix #5177

### CODE REVIEW

**Comment by karthiknadig** [comment]
enable the Set next statement UI tests.

**Comment by karthiknadig** [comment]
For this to work correctly you will need a fix from ptvsd. The fix is in master. I will make a new release soon.

**Comment by karthiknadig** [comment]
Look here for the changes you might need to enable tests for set next statement: https://github.com/Microsoft/PTVS/compare/master...karthiknadig:setnext?expand=1

**Comment by huguesv** [comment]
Changes in karthik's branch seem to be passing
image
image

I think we can take his changes, after final release of ptvsd 4.2.8 is done

**Comment by karthiknadig** [comment]
4.2.8 released https://pypi.org/project/ptvsd/4.2.8/

**Comment by RaymonGulati1** [comment]
Closed because
https://github.com/Microsoft/PTVS/pull/5244

**Pull request closed without merging**
