### PR TITLE
Fixes #4434 No imports without Python installed

### LINKED ISSUE #3802: TestDiscovererTests failures
- DecoratedTests
- TestCaseRunTests
- TestCaseRunTestsWithTest
- TestCaseSubclasses

I tested all 4 scenarios manually and they work fine in the product, so it's a matter of fixing the tests so we stop thinking the product is broken.

### LINKED ISSUE #4434: No imports without Python installed
We include default databases with the install for when you don't have Python installed, but we aren't using them.

### PR DESCRIPTION
**Pull request by zooba**
Fixes #4434 No imports without Python installed
Fixes #3802 TestDiscovererTests failures
Replace NoInterpretersFactory with analysis-only factory

### CODE REVIEW

**Comment by huguesv** [comment]
What are your results for `TestDiscovererTests`? Only `TestDiscover` passes for me. All others get 0 results. I'm not sure that `TestDiscover` even does any parsing/analysis of code to find tests, it looks it's just validating the parsing of the run settings.

**Comment by zooba** [comment]
It needs the fix from #4452 as well, I think. I rebased onto a new branch for the PR.

**Comment by zooba** [comment]
Or you need to force a full rebuild to regenerate `DefaultDB`. It doesn't automatically refresh like the regular cache does.

**Comment by huguesv** [comment]
I got both PRs and did a full rebuild and now all TestDiscovererTests pass.

**Pull request merged**
