### PR TITLE
Updates skip verification scripts for UWP.

### PR DESCRIPTION
**Pull request by zooba**

### CODE REVIEW

**Comment by int19h** [comment]
Can you add this to .gitattributes while you're at it (to enable text diffing for those files)?
```
*.reg diff
```

**Comment by zooba** [comment]
Was just looking into that, but they're UTF-16 with a BOM, so it's not going to work anyway (every reference I've seen so far says that git barfs on anything that isn't ANSI, which was my understanding).

**Comment by int19h** [comment]
They're UTF-16 because that's what regedit exports in by default, but it accepts ASCII as input just fine, so you can just save them as the latter.

**Comment by zooba** [comment]
I think they're still marked as binary because of the previous version and not because of .gitattributes. If it's still an issue we can fix that up later.

**Comment by int19h** [comment]
:+1:

**Pull request merged**
