### PR TITLE
Fixes #450 NullReferenceException testing test adapter

### LINKED ISSUE #450: NullReferenceException testing test adapter
```
First-chance exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.PythonTools.TestAdapter.TestExecutor.RunTestCase(IFrameworkHandle frameworkHandle, IRunContext runContext, TestCase test, Dictionary`2 sourceToSettings) in C:\Source\Python\Product\TestAdapter\TestExecutor.cs:line 146
```

Looks like this may also be breaking the entire test run and causing lots of skips.

### PR DESCRIPTION
**Pull request by zooba**
Fixes #450 NullReferenceException testing test adapter
Adds missing null check for _app.

### CODE REVIEW

**Comment by gilbertw** [comment]
:+1:

**Comment by huguesv** [comment]
Will we now just crash later at line 216 when it uses `_app` without checking for null?

**Comment by zooba** [comment]
If `_app` is null then the debug mode is None, so we won't hit the later case (but we still need DTE to find some VS settings if we can get it).

**Comment by huguesv** [comment]
:+1:

**Pull request merged**
