### PR TITLE
Fixes #4438 Signatures not merging properly with typeshed

### LINKED ISSUE #4438: Signatures not merging properly with typeshed
The below signature comes partially from typeshed and partially from our analysis. We should be merging better than this.

image

### PR DESCRIPTION
**Pull request by zooba**
Fixes #4438 Signatures not merging properly with typeshed
Skips leading parameters when we mean to replace rather than extend
Fixes tuple syntax
Fixes intersection tests

### CODE REVIEW

**Comment by huguesv** [comment]
`TypeShedJsonMakeScanner` is not passing for me (it's using Python 3.7 32-bit)
```
Test Name:	TypeShedJsonMakeScanner
Test FullName:	AnalysisTests.AstAnalysisTests.TypeShedJsonMakeScanner
Test Source:	C:\Projects\GitHub\huguesv\PTVS\Python\Tests\Analysis\AstAnalysisTests.cs : line 1068
Test Outcome:	Failed
Test Duration:	0:00:29.9918277

Result StackTrace:	
at TestUtilities.AssertUtil.ContainsExactly[T](HashSet`1 set, T[] expected) in C:\Projects\GitHub\huguesv\PTVS\Common\Tests\Utilities\AssertUtil.cs:line 231
   at TestUtilities.AssertUtil.ContainsExactly[T](IEnumerable`1 source, T[] expected) in C:\Projects\GitHub\huguesv\PTVS\Common\Tests\Utilities\AssertUtil.cs:line 222
   at AnalysisTests.AstAnalysisTests.TypeShedJsonMakeScanner() in C:\Projects\GitHub\huguesv\PTVS\Python\Tests\Analysis\AstAnalysisTests.cs:line 1078
Result Message:	Assert.Fail failed. ContainsExactly failed.

Expected:
{__call__(string:str=,index:int=)->[tuple[int, None, ]]}

Actual:
{__call__(string:str=,index:int=)->[tuple[None, int]]}

Expected not in actual:
{__call__(string:str=,index:int=)->[tuple[int, None, ]]}

Actual not in expected:
{__call__(string:str=,index:int=)->[tuple[None, int]]}
Result StandardOutput:	
Creating temp directory for test at C:\Users\huvalo\AppData\Local\Temp\gvjtiv1a.zgz\AstAnalysisCache\
Creating temp directory for test at C:\Users\huvalo\AppData\Local\Temp\gvjtiv1a.zgz\ltbxwwuc.u3k\

```

**Comment by huguesv** [comment]
`TypeShedSysExcInfo` test passes, but when I try to do it in the editor, I don't see any types for e1,e2,e3 and no completions. That used to work some time ago when I pip installed the typeshed package, and I hadn't tested that one since.
image

**Comment by zooba** [comment]
Heh, because I made it work and then fixed the other test properly...

**Comment by zooba** [comment]
No, you're right, I'm not getting them either... weird...

**Comment by huguesv** [comment]
It's not a regression from this PR, so we can fix it separately. Up to you.

**Comment by zooba** [comment]
It's looking like a bigger change (to handle `typing` properly without importing the actual file), so I'll do it separately.

**Pull request merged**
