### PR TITLE
Fixes code analysis warnings.

### PR DESCRIPTION
**Pull request by zooba**
The two lock disposes are the only risky parts of this change at all, and I'm fairly sure they're fine.

I haven't fixed any of the complaints about all the classes that should have IDisposable, only the ones that were already disposable but weren't disposing everything.

### CODE REVIEW

**Comment by int19h** [comment]
:+1: , but does it meet the bar?

**Comment by zooba** [comment]
Depends how you interpreter the "FxCop clean" release security requirement... I don't think any of these are on the security-specific list, so probably not.

**Comment by huguesv** [comment]
:+1:

**Comment by crwilcox** [comment]
:+1:

**Pull request merged**
