### PR TITLE
Fixes #2260 Start with/without debugging launches the wrong file

### LINKED ISSUE #2260: Start with/without debugging launches the wrong file
Open a python project
Drag & drop a python file that doesn't belong in that project into the editor
Right-click on editor and select Start with debugging, or Start without Debugging.

Result: The project's startup file is launched, instead of the file that you right-clicked on.

`DebugProject.StartWithoutDebuggingNotInProject` fails while doing these exact steps.

### PR DESCRIPTION
**Pull request by zooba**
Fixes #2260 Start with/without debugging launches the wrong file
Removes global command handlers and handles them in the edit filter and project nodes.
Corrects the issue identified in #2129 for EditFilter
Fixes potential infinite loop when abandoning out-of-proc analyzers

### CODE REVIEW

**Comment by int19h** [comment]
👍

**Comment by huguesv** [comment]
👍  I'll retest remote debugging to Azure VM to ensure the stream reading change doesn't break it.

**Comment by zooba** [comment]
It should be an okay change because of the `await` - if the stream is still alive but there's nothing to read it will wait, and it's only when the stream is actually complete (but not closed) that it exits. But I didn't test any of the cases where we provide a stream to it (rather than stdio), so I'll do a quick check before merging.

**Comment by zooba** [comment]
It has no impact on local-remote debugging, and I don't see any reason why remote-remote debugging would be different. But please retest that once the build comes out.

**Pull request merged**
